#!/usr/bin/env bash
# Regenerates the committed test fixtures in ../test/data, using only the tools in ../tools.
#
# Every CSV lives in ../test/data, next to the fixtures it produces. The demo's CSVs are separate, in this
# directory: it wants data that shows off a bit matrix, while the tests want columns whose ranges are
# disjoint between the two files, which is what the bounds assertions are built on.
#
# Needs a vanilla duckdb on PATH, or $F8_DUCKDB pointing at one - no f8 required to write these files.
#
# The point of generating them this way is that the fixtures the tests run against are produced by
# the same path a user would take, rather than by something that only exists inside the test.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tools="$here/../tools"
data="$here/../test/data"

# Two example modules, both implementing the whole ABI. min_max carries per-column bounds and nothing
# else; min_maxtrix adds a bit matrix per column pair, and answers a conjunction that bounds cannot.
echo "== building the filter modules =="
"$tools/build_f8_module" "$here/min_max/f8_min_max_module.c" "$data/f8_min_max_module.wasm"
"$tools/build_f8_module" "$here/min_maxtrix/f8_min_maxtrix_module.c" "$data/f8_min_maxtrix_module.wasm"

# min_max with the f8_conj_i64 export removed, so a test can tell which entry point the host chose for a
# given predicate shape. Bounds give the same verdict whether a pair is asked jointly or one term at a
# time, so nothing else distinguishes them.
echo
echo "== building the equal-only module, the routing tripwire =="
equal_only="$(mktemp -d)/f8_equal_only_module.c"
{
    echo "// GENERATED by regenerate-fixtures.sh from min_max/f8_min_max_module.c - do not edit."
    sed '/EXPORT("f8_conj_i64")/d' "$here/min_max/f8_min_max_module.c"
} > "$equal_only"
"$tools/build_f8_module" "$equal_only" "$data/f8_equal_only_module.wasm"

# Only plain parquet files are committed. The tests embed the module and metadata themselves, which is
# what exercises the read path against bytes it did not create.
for csv in "$data/a.csv" "$data/b.csv" "$data/two.csv" "$data/wide.csv" "$data/triple.csv"; do
    name="$(basename "$csv" .csv)"
    echo
    echo "== $name =="
    "$here/min_maxtrix/f8_min_maxtrix_metadata_generator" "$csv" "$data/metadata_$name.bin"
    "$tools/embed_f8_in_parquet" "$csv" "$data/plain_$name.parquet"
done

echo
echo "== fixtures =="
ls -l "$data" | awk 'NR>1 {printf "  %8d  %s\n", $5, $9}'
